### ISSUE TITLE
sfdx ngx:build giving error 

### ISSUE THREAD

**Issue by ghost** [rzhigalov/sfdx-ngx-plugin#6]
I am giving build from windows . Can you please fix this issue.

sfdx ngx:build
=== Building Angular project for SFDC
{ Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs:
   [ 'run', 'build', '--', '--deployUrl=%%SFDC_RESOURCE_TOKEN%%' ] }
{ Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs:
   [ 'run', 'build', '--', '--deployUrl=%%SFDC_RESOURCE_TOKEN%%' ] }
{ Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs:
   [ 'run', 'build', '--', '--deployUrl=%%SFDC_RESOURCE_TOKEN%%' ] }

**Comment by rzhigalov** [comment]
Hi @lijolijojohn 
Sorry for the long silence – it has been a busy period.

Can you provide a little additional info:
1. What windows version are you running?
2. Node.js, sfdx and Angular CLI versions.

Looking forward for your reply!
